-- =============================================================================
-- MASTER SETUP SCRIPT FOR BANGALI ENTERPRISE
-- =============================================================================
-- This script does EVERYTHING:
-- 1. Creates all Database Tables (Profiles, Businesses, Products, etc.)
-- 2. Sets up Security Policies (RLS)
-- 3. Creates the 'Abul Khayer Consumers' retail business
-- 4. Links your specific Admin, Owner, Manager, and Seller accounts
-- =============================================================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- =============================================================================
-- PART 1: BASE TABLES
-- =============================================================================

-- 1. PROFILES (Users)
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    email text unique,
    full_name text,
    role text default 'viewer', -- global_admin, owner, manager, seller, viewer
    business_id uuid,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.profiles enable row level security;

-- 2. BUSINESSES
create table if not exists public.businesses (
    id uuid default uuid_generate_v4() primary key,
    name text not null,
    type text not null default 'retail_store',
    owner_id uuid references public.profiles(id),
    subscription_status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.businesses enable row level security;

-- Fix circular dependency: Add FK to profiles
alter table public.profiles 
drop constraint if exists profiles_business_id_fkey,
add constraint profiles_business_id_fkey foreign key (business_id) references public.businesses(id) on delete set null;

-- 3. BUSINESS TYPES
drop table if exists public.business_types cascade;
create table public.business_types (
    id text primary key,
    name text not null,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.business_types enable row level security;
create policy "Read business types" on business_types for select using (true);

-- Seed Business Types
insert into public.business_types (id, name) values
    ('retail_store', 'Retail Store'),
    ('service_provider', 'Service Provider'),
    ('agency', 'Agency'),
    ('freelancer', 'Freelancer'),
    ('education', 'Education'),
    ('other_business', 'Other Business')
on conflict (id) do nothing;

-- 4. BUSINESS USERS (M:N Relationship)
create table if not exists public.business_users (
    id uuid default uuid_generate_v4() primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    user_id uuid references public.profiles(id) on delete cascade not null,
    role text not null check (role in ('owner', 'manager', 'seller', 'viewer')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(business_id, user_id)
);
alter table public.business_users enable row level security;

-- 5. PRODUCTS
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    name text not null,
    description text,
    price numeric default 0,
    cost_price numeric default 0,
    stock_qty integer default 0,
    category text,
    supplier text,
    image_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.products enable row level security;

-- 6. CATEGORIES
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    name text not null,
    type text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.categories enable row level security;

-- 7. SUPPLIERS
create table if not exists public.suppliers (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    name text not null,
    contact_info text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.suppliers enable row level security;

-- 8. CUSTOMERS
create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    name text not null,
    phone text,
    email text,
    address text,
    current_due numeric default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.customers enable row level security;

-- 9. ORDERS
create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    customer_id bigint references public.customers(id) on delete set null,
    order_number text,
    total_amount numeric default 0,
    status text default 'pending',
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.orders enable row level security;

-- 10. ORDER ITEMS
create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id) on delete cascade not null,
    product_id bigint references public.products(id) on delete set null,
    quantity integer default 1,
    unit_price numeric default 0,
    total_price numeric default 0
);
alter table public.order_items enable row level security;

-- 11. SALES TRANSACTIONS
create table if not exists public.sales_transactions (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    customer_id bigint references public.customers(id),
    invoice_number text,
    subtotal numeric default 0,
    discount numeric default 0,
    tax numeric default 0,
    total_amount numeric default 0,
    payment_method text,
    status text default 'completed',
    served_by uuid references public.profiles(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.sales_transactions enable row level security;

-- 12. SALES ITEMS
create table if not exists public.sales_items (
    id bigint generated by default as identity primary key,
    transaction_id bigint references public.sales_transactions(id) on delete cascade not null,
    product_id bigint references public.products(id),
    product_name text,
    quantity integer default 1,
    unit_price numeric default 0,
    total_price numeric default 0
);
alter table public.sales_items enable row level security;

-- 13. EXPENSES
create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    amount numeric default 0,
    category text,
    description text,
    date timestamp with time zone default timezone('utc'::text, now()),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.expenses enable row level security;

-- 14. SYSTEM SETTINGS
drop table if exists public.system_settings cascade;
create table public.system_settings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    settings jsonb not null default '{}'::jsonb,
    is_active boolean default true
);
alter table public.system_settings enable row level security;

-- 15. BUSINESS SETTINGS
create table if not exists public.business_settings (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    settings jsonb not null default '{}'::jsonb,
    constraint business_settings_business_id_key unique (business_id)
);
alter table public.business_settings enable row level security;

-- 16. AUDIT LOGS
create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    action text not null,
    actor_id uuid references public.profiles(id),
    details jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.audit_logs enable row level security;

-- 17. COMMISSIONS
create table if not exists public.commissions (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    user_id uuid references public.profiles(id) on delete cascade not null,
    amount numeric default 0,
    source_type text, -- 'sale', 'project'
    source_id text,
    status text default 'pending', -- pending, paid
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.commissions enable row level security;

-- 18. PROJECTS (Agency/Freelancer)
create table if not exists public.projects (
    id uuid default uuid_generate_v4() primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    client_id bigint references public.customers(id) on delete set null,
    name text not null,
    description text,
    status text default 'active',
    budget numeric default 0,
    deadline timestamp with time zone,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.projects enable row level security;

-- 19. TIME ENTRIES (Freelancer/Agency)
create table if not exists public.time_entries (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    project_id uuid references public.projects(id) on delete cascade,
    user_id uuid references public.profiles(id) on delete cascade not null,
    description text,
    start_time timestamp with time zone not null,
    end_time timestamp with time zone,
    duration_minutes integer,
    is_billable boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.time_entries enable row level security;

-- 20. APPOINTMENTS (Service)
create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    customer_id bigint references public.customers(id) on delete cascade,
    service_id bigint, -- References products(id) where category='service'
    staff_id uuid references public.profiles(id),
    appointment_time timestamp with time zone not null,
    status text default 'scheduled', -- scheduled, completed, cancelled
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.appointments enable row level security;

-- 21. COURSES (Education)
create table if not exists public.courses (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    name text not null,
    code text,
    description text,
    fee numeric default 0,
    instructor_id uuid references public.profiles(id),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.courses enable row level security;

-- 22. STUDENTS (Education)
create table if not exists public.students (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    user_id uuid references public.profiles(id), -- Optional link to auth user
    full_name text not null,
    email text,
    phone text,
    enrollment_date date default now(),
    status text default 'active',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.students enable row level security;

-- 23. WHOLESALE PRICE TIERS
create table if not exists public.price_tiers (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    name text not null, -- e.g., 'Gold Distributor', 'Silver'
    min_quantity integer default 0,
    discount_percentage numeric default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.price_tiers enable row level security;

-- 24. MANUFACTURING ORDERS
create table if not exists public.production_orders (
    id bigint generated by default as identity primary key,
    business_id uuid references public.businesses(id) on delete cascade not null,
    product_id bigint references public.products(id), -- Finished good
    quantity integer default 1,
    status text default 'planned', -- planned, in_progress, completed
    start_date date,
    end_date date,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.production_orders enable row level security;

-- =============================================================================
-- PART 2: ROW LEVEL SECURITY POLICIES
-- =============================================================================

-- Profiles
drop policy if exists "Public profiles are viewable by everyone" on profiles;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Businesses
drop policy if exists "Businesses viewable by authenticated" on businesses;
create policy "Businesses viewable by authenticated" on businesses for select to authenticated using (true);
drop policy if exists "Owners can update business" on businesses;
create policy "Owners can update business" on businesses for update using (auth.uid() = owner_id);

-- Business Users (Teams)
drop policy if exists "Users can view own memberships" on business_users;
create policy "Users can view own memberships" on business_users for select using (auth.uid() = user_id);

drop policy if exists "Global Admin full access" on business_users;
create policy "Global Admin full access" on business_users for all using (
    exists (select 1 from profiles where id = auth.uid() and role = 'global_admin')
);

drop policy if exists "Owners manage their business" on business_users;
create policy "Owners manage their business" on business_users for all using (
    exists (
        select 1 from business_users bu
        where bu.business_id = business_users.business_id
        and bu.user_id = auth.uid()
        and bu.role = 'owner'
    )
);

-- General Data Tables (Allow authenticated for now, simpler for MVP)
create policy "Authenticated can view products" on products for select to authenticated using (true);
create policy "Authenticated can insert products" on products for insert to authenticated with check (true);
create policy "Authenticated can update products" on products for update to authenticated using (true);
create policy "Authenticated can delete products" on products for delete to authenticated using (true);

create policy "Enable all for orders" on orders for all using (true);
create policy "Enable all for order_items" on order_items for all using (true);
create policy "Enable all for sales" on sales_transactions for all using (true);
create policy "Enable all for sales_items" on sales_items for all using (true);
create policy "Enable all for customers" on customers for all using (true);
create policy "Enable all for expenses" on expenses for all using (true);
create policy "Enable all for categories" on categories for all using (true);
create policy "Enable all for suppliers" on suppliers for all using (true);
create policy "Enable all for business_settings" on business_settings for all using (true);

-- New Tables Policies
create policy "Enable all for commissions" on commissions for all using (true);
create policy "Enable all for projects" on projects for all using (true);
create policy "Enable all for time_entries" on time_entries for all using (true);
create policy "Enable all for appointments" on appointments for all using (true);
create policy "Enable all for courses" on courses for all using (true);
create policy "Enable all for students" on students for all using (true);
create policy "Enable all for price_tiers" on price_tiers for all using (true);
create policy "Enable all for production_orders" on production_orders for all using (true);

-- System Settings
create policy "System settings read all" on system_settings for select using (true);
create policy "System settings update admin" on system_settings for update using (
  exists (select 1 from profiles where id = auth.uid() and role = 'global_admin')
);

-- =============================================================================
-- PART 3: DATA SEEDING & ACCOUNT LINKING
-- =============================================================================

-- Initial System Settings
insert into public.system_settings (settings)
select '{"platform_name": "Bangali Enterprise", "currency": "BDT (৳)", "session_timeout": 60}'::jsonb
where not exists (select 1 from public.system_settings);

-- LINK ACCOUNTS & CREATE RETAIL BUSINESS
DO $$
DECLARE
    retail_biz_id UUID;
    admin_uid UUID;
    owner_uid UUID;
    manager_uid UUID;
    seller_uid UUID;
BEGIN
    -- 1. Create the RETAIL Business "Abul Khayer Consumers"
    SELECT id INTO retail_biz_id FROM public.businesses WHERE name = 'Abul Khayer Consumers' LIMIT 1;
    
    IF retail_biz_id IS NULL THEN
        INSERT INTO public.businesses (name, type, subscription_status)
        VALUES ('Abul Khayer Consumers', 'retail_store', 'active')
        RETURNING id INTO retail_biz_id;
    END IF;

    -- 2. Get User IDs (Using emails)
    SELECT id INTO admin_uid FROM auth.users WHERE email = 'admin@bangalienterprise.com';
    SELECT id INTO owner_uid FROM auth.users WHERE email = 'enterprisebangali@gmail.com';
    SELECT id INTO manager_uid FROM auth.users WHERE email = 'arifhossenrakib001@gmail.com';
    SELECT id INTO seller_uid FROM auth.users WHERE email = 'mrak@virgilian.com';

    -- 3. LINK SUPER ADMIN
    IF admin_uid IS NOT NULL THEN
        INSERT INTO public.profiles (id, full_name, email, role, business_id)
        VALUES (admin_uid, 'Platform CEO', 'admin@bangalienterprise.com', 'global_admin', NULL)
        ON CONFLICT (id) DO UPDATE SET role = 'global_admin';
    END IF;

    -- 4. LINK RETAIL OWNER
    IF owner_uid IS NOT NULL THEN
        INSERT INTO public.profiles (id, full_name, email, role, business_id)
        VALUES (owner_uid, 'Arif Hossen Rakib', 'enterprisebangali@gmail.com', 'owner', retail_biz_id)
        ON CONFLICT (id) DO UPDATE SET role = 'owner', business_id = retail_biz_id;
        
        -- Insert into User-Business (Teams)
        INSERT INTO public.business_users (business_id, user_id, role)
        VALUES (retail_biz_id, owner_uid, 'owner')
        ON CONFLICT (business_id, user_id) DO UPDATE SET role = 'owner';

        -- Update business owner
        UPDATE public.businesses SET owner_id = owner_uid WHERE id = retail_biz_id;
    END IF;

    -- 5. LINK MANAGER
    IF manager_uid IS NOT NULL THEN
        INSERT INTO public.profiles (id, full_name, email, role, business_id)
        VALUES (manager_uid, 'Retail Manager', 'arifhossenrakib001@gmail.com', 'manager', retail_biz_id)
        ON CONFLICT (id) DO UPDATE SET role = 'manager', business_id = retail_biz_id;

        INSERT INTO public.business_users (business_id, user_id, role)
        VALUES (retail_biz_id, manager_uid, 'manager')
        ON CONFLICT (business_id, user_id) DO UPDATE SET role = 'manager';
    END IF;

    -- 6. LINK SELLER
    IF seller_uid IS NOT NULL THEN
        INSERT INTO public.profiles (id, full_name, email, role, business_id)
        VALUES (seller_uid, 'Retail Seller', 'mrak@virgilian.com', 'seller', retail_biz_id)
        ON CONFLICT (id) DO UPDATE SET role = 'seller', business_id = retail_biz_id;

        INSERT INTO public.business_users (business_id, user_id, role)
        VALUES (retail_biz_id, seller_uid, 'seller')
        ON CONFLICT (business_id, user_id) DO UPDATE SET role = 'seller';
    END IF;

    RAISE NOTICE 'SUCCESS: Database fully setup. Business "Abul Khayer Consumers" created and users linked.';
END $$;
